name: Continuous Integration

on:
  pull_request:
    branches:
      - main

#concurrency:
#  group: ci-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: .nvmrc
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Code linting
        run: npm run lint
